import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers , AuthBootstrapc}from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vibe Code Live ",
  description: "Generated by create next app",
  verification: {
    google: "36c2_gS965wsrumHSor0n2bjd7AAsVCpDmo-Y2ezwNI",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthBootstrapc>{children}</AuthBootstrapc>
        </Providers>
      </body>
    </html>
  );
}
